# Generated by Django 3.0.1 on 2020-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200106_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
